name: dropbox
description: Dropbox client for Dart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.13.1 <3.0.0'


dependencies:
  file: ^6.0.0
  logging: ^1.0.1
  http: ^0.13.3
  crypto: ^3.0.1
  quiver: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dotenv: ^3.0.0
